### ISSUE TITLE
gwascatalog.ttl unparsable Integer

### ISSUE THREAD

**Issue by jnguyenx** [monarch-initiative/dipper#399]
Scigraph reports some warnings:
```
WARNING: For input string: "191150346;191145762;191153045"
java.lang.NumberFormatException: For input string: "191150346;191145762;191153045"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at uk.ac.manchester.cs.owl.owlapi.OWLLiteralImplNoCompression.parseInteger(OWLLiteralImplNoCompression.java:114)
	at io.scigraph.owlapi.OwlApiUtils.getTypedLiteralValue(OwlApiUtils.java:74)
	at io.scigraph.owlapi.GraphOwlVisitor.visit(GraphOwlVisitor.java:303)
	at io.scigraph.owlapi.GraphOwlVisitor.visit(GraphOwlVisitor.java:84)
	at uk.ac.manchester.cs.owl.owlapi.OWLDataPropertyAssertionAxiomImpl.accept(OWLDataPropertyAssertionAxiomImpl.java:129)
	at io.scigraph.owlapi.loader.OwlOntologyConsumer.call(OwlOntologyConsumer.java:72)
	at io.scigraph.owlapi.loader.OwlOntologyConsumer.call(OwlOntologyConsumer.java:35)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Those numbers seem to come from gwascatalog.ttl:
```
monarch-ttl-prod:/var/www/data/ttl$ grep -R "191150346;191145762;191153045"
gwascatalog.ttl:    faldo:location <https://monarchinitiative.org/_GRCh38chr2;2;2-191150346;191145762;191153045-191150346;191145762;191153045-Region> ;
gwascatalog.ttl:<https://monarchinitiative.org/_GRCh38chr2;2;2-191150346;191145762;191153045-191150346;191145762;191153045-Region> a faldo:Region ;
gwascatalog.ttl:    faldo:begin <https://monarchinitiative.org/_GRCh38chr2;2;2-191150346;191145762;191153045> ;
gwascatalog.ttl:    faldo:end <https://monarchinitiative.org/_GRCh38chr2;2;2-191150346;191145762;191153045> .
gwascatalog.ttl:<https://monarchinitiative.org/_GRCh38chr2;2;2-191150346;191145762;191153045> a faldo:Position ;
gwascatalog.ttl:    faldo:position "191150346;191145762;191153045"^^xsd:integer ;

```

**Comment by kshefchek** [comment]
These appear to be haplotypes, here is a strawman model:

        ?genotype a GENO:0000000 ;
            a SO:0001024 ;
           RO:0002326 EFO:1234 ;
           GENO_0000382 dbsnp:rs123
           GENO_0000382 dbsnp:rs345


SO:0001024 ! haplotype
GENO:0000000 ! intrinsic genotype (sex-agnostic)
RO:0002326 ! contributes to
GENO:0000382 ! has variant part

The rest of the modelling (associations, snp to feature location) should stay the same.

Note this means we need to mint genotype ids for haplotypes.  Also see: https://github.com/monarch-initiative/GENO-ontology/issues/23

**Comment by kshefchek** [comment]
@TomConlin assigning to you since it sounds like you have a start, but feel free to assign back to me if you are busy.
